### ISSUE TITLE
[BUG] Download of host-specific Agent is not always correct

### ISSUE THREAD

**Issue by HaZet1968** [tribe29/ansible-collection-tribe29.checkmk#210] opened 2022-12-20 10:05 UTC
**Describe the bug**
Download of host-specific Agent is not always correct. If checkmk_agent_host_name <> inventory_hostname download fails.
Reason: cmk Server does not know about the inventory_hostname.

**Component Name**
Download host-specific Checkmk {{ checkmk_agent_edition | upper }} Agent in Debian.yml. But Suse and Redhat also affected

**Checkmk Version**
2.1.0p17
```console
CEE
```

**Expected behavior**
Download Host specific Agent

**Actual behavior**
```
TASK [tribe29.checkmk.agent : Debian Derivatives: Download host-specific Checkmk CEE Agent.] ***************************************************
ok: [xxxx -> xxxx] => {"changed": false, "connection": "close", "content_length": "155", "content_security_policy": "default-src 'self' 'unsafe-inline' 'unsafe-eval' ssh: rdp:; img-src 'self' data: https://*.tile.openstreetmap.org/ ; connect-src 'self' https://crash.checkmk.com/ https://license.checkmk.com/api/upload ; frame-ancestors 'self' ; base-uri 'self'; form-action 'self' javascript: 'unsafe-inline'; object-src 'self'; worker-src 'self' blob:", "content_type": "application/problem+json", "date": "Tue, 20 Dec 2022 09:29:10 GMT", "elapsed": 0, "failed_when_result": false, "json": {"detail": **"These fields have problems: host_name", "fields": {"host_name": ["Host not found: 'xxxx'"]}**, "status": 400, "title": "Bad Request"}, "msg": "Status code was 400 and not [200]: HTTP Error 400: BAD REQUEST", "path": "/tmp/check-mk-agent_2.1.0p17-xxxx.deb", "permissions_policy": "accelerometer=(), autoplay=(), camera=(), encrypted-media=(), fullscreen=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), usb=()", "redirected": false, "referrer_policy": "origin-when-cross-origin", "server": "Apache", "status": 400, "url": "https://yyyyyyyyyy.de:443/site/check_mk/api/1.0/domain-types/agent/actions/download_by_host/invoke?host_name=xxxxxx&os_type=linux_deb&agent_type=host_name", "x_content_type_options": "nosniff", "x_frame_options": "sameorigin", "x_permitted_cross_domain_policies": "none", "x_xss_protection": "1; mode=block"}
```

**Screenshots**

**Additional context**
After changing the url from
`url: "{{ checkmk_agent_agent.url.cee }}?host_name={{ inventory_hostname }}&os_type=linux_deb&agent_type=host_name"`
to
`url: "{{ checkmk_agent_agent.url.cee }}?host_name={{ checkmk_agent_host_name }}&os_type=linux_deb&agent_type=host_name"`

in Debian.yml it works for me.

**Comment by robin-tribe29** [comment] 2022-12-20 11:23
Hello @HaZet1968 and thanks for your feedback!

While I understand your issue, this is at least kind of by design. You need one single source of truth and in our experience, local hostnames are far worse than an e.g. Ansible inventory. But I see room for improvement, by making this configurable with a sane default. If you feel up to the task, I would love to see your pull request. If not, we will look into this, once we find the time.

I updated the issue to reflect our point of view on the situation.

**Comment by robin-tribe29** [comment] 2022-12-23 08:37
@HaZet1968 quick update: I now understood the problem in full and fixed is just as you described. This issue will close, once the changes make it to the main branch. So this will probably be fixed with the first release of next year.

**Comment by HaZet1968** [comment] 2023-01-03 13:23
Sorry, wasn't at work the last two weeks. But as far as I see you understood what I mean

**Comment by HaZet1968** [comment] 2023-01-03 13:25
Sorry, wasn't at work the last two weeks, but as far as I see you know what I mean

**Closed** 2023-01-11 10:45 UTC
Labels: bug, role:agent
